services:
  db:
    image: mongo:8.0.5
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  rabbit:
    image: rabbitmq:3.13.7-management
    container_name: rabbit
    ports:
      - "5672:5672"   # Queue port
      - "15672:15672" # Management port
    restart: always

  storage:
    image: storage
    build:
      context: ./storage
      dockerfile: Dockerfile-prod
    container_name: storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
    restart: "no"

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    container_name: video-streaming-backend
    ports:
      - "4002:3000"
    environment:
      - PORT=3000
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=storage
      - VIDEO_STORAGE_PORT=80
      - HISTORY_PORT=80
    depends_on:
      - db
      - rabbit
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-prod
    container_name: history
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
    depends_on:
      - db
      - rabbit
    restart: "no"

  users:
    image: users
    build:
      context: ./users
      dockerfile: Dockerfile-prod
    container_name: users
    ports:
      - "4004:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    restart: "no"