[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
awc = "3.5.1"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"]}
