[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.9.0"
azure_storage = "0.21.0"
azure_storage_blobs = "0.21.0"
serde = { version = "1.0.218", features = ["derive"] }