name: Build and Push Microservices to ghcr

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, '[publish]')
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_OWNER: ${{ github.repository_owner }}
      TAG_NAME: ${{ github.ref_name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Docker tag name from commit message
      run: |
        if [[ "${{ github.event.head_commit.message }}" =~ \[tag=(.*)\] ]]; then
          echo "TAG_NAME=${BASH_REMATCH[1]}" >> $GITHUB_ENV
        fi

    - name: Log in to Github Container REGISTRY
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Images
      run: |

        OWNER_LOWER=$(echo "${{ env.IMAGE_OWNER }}" | tr '[:upper:]' '[:lower:]')
        services=("backend" "history" "recommendations" "storage")

        for service in "${services[@]}"; do
          IMAGE_NAME=${{ env.REGISTRY }}/$OWNER_LOWER/rusttube/$service

          echo "Building and pushing $IMAGE_NAME:latest and $IMAGE_NAME:${{ env.TAG_NAME }}"

          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ env.TAG_NAME }} -f ./$service/Dockerfile-prod ./$service
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ env.TAG_NAME }}
        done